const loginRouter = require("../routes/login")
const registerRouter = require("../routes/register")
const profileRouter = require ("../routes/profile")
const storageImage = require ("../storage/images/storage")
const searchRouter = require("../routes/search")
const provinceRouter = require ("../routes/addressRouter/province")
const reactRouter = require("../routes/react")
const viewRouter = require("../routes/view")
const chatRouter = require("../routes/chat")
function route(app){
  app.use("/register",registerRouter)
  app.use("/profile"  ,profileRouter) 
  app.use("/search",searchRouter)
  app.use("/address",provinceRouter)
  app.use("/react",reactRouter)
  app.use("/view", viewRouter)
  app.use("/chat",chatRouter)
  app.use("/", loginRouter)
}
module.exports = route